#!/bin/bash
echo "=== Pure-Go GGUF Runtime - Demo ==="
echo ""
echo "1. Inspecting GGUF Model:"
echo "---"
./gguf-inspect models/All-MiniLM-L6-v2-Embedding-GGUF/all-MiniLM-L6-v2-Q8_0.gguf | head -25
echo ""
echo "2. Running Integration Tests:"
echo "---"
go test -v ./internal/gguf -tags=integration -run TestRealModelLoad 2>&1 | grep -E "RUN|PASS|Model|Version|Tensors|Architecture|dimension"
echo ""
echo "3. Testing Q8_0 Numerical Accuracy:"
echo "---"
go test -v ./internal/kernels -tags=integration -run TestMatMulWithRealQ8_0 2>&1 | grep -E "RUN|PASS|Testing|accuracy|Max difference"
echo ""
echo "=== All Core Components Working! ✅ ==="
